### ISSUE TITLE
[Bug] Sending two configured user properties results in receiving three

### ISSUE THREAD

**Issue by MartinL0815** [emqx/MQTTX#815] opened 2021-12-08 13:27 UTC
#### What did I do

I configured MQTTX 1.7 to send with a publish two user properties:

> ![Meta configuration](https://user-images.githubusercontent.com/525700/145215675-788b9d61-cfed-4067-9d77-ec3eb427de6c.png)

#### What happened

In the receiving client I receive three user properties:

> ![Received MQTT properties](https://user-images.githubusercontent.com/525700/145215807-190e3ba5-d103-4261-bc50-104e90462532.png)

#### Expected

I expected to receive only the two configure (see above) user properties.

#### Environment

- OS: MS Windows 10 Enterprise Version 1909 build 18636.1854
- MQTTX version 1.7.0

**Comment by ysfscream** [comment] 2021-12-09 01:59
Hi! @MartinL0815 YES! I didn't find this problem before this and this issue is caused by JavaScript Framework Vue.js, I will fix it right away, thanks for your feedback. ref: https://guillim.github.io/vue/2019/03/20/damn-vuejs-observer.html

**Comment by ysfscream** [comment] 2021-12-31 07:36
Fixed on https://github.com/emqx/MQTTX/releases/tag/v1.7.1, I will close this issue.

**Closed by ysfscream** 2021-12-31 07:36 UTC
Labels: bug
