### ISSUE TITLE
[Bug] 下一个启动的连接可能会错误的使用上一个启动连接的clientid

### ISSUE THREAD

**Issue by LLLLimbo** [emqx/MQTTX#910] opened 2022-03-08 00:12 UTC
当前使用的版本为1.7.3
第一个连接和第二个连接分别为
![image](https://user-images.githubusercontent.com/31607003/157139710-17ea6ed0-621d-47a2-b787-7d44ccfba805.png)
![image](https://user-images.githubusercontent.com/31607003/157139748-441f3a5f-8896-4686-8033-951d129a1f91.png)
当我先启动第一个连接，再启动第二个连接后，MQTT Broker的日志显示`local_1001`这个客户端由于另一个同名client_id出现而被断开连接，该操作可以复现
`[9604] 2022/03/08 07:57:59.514766 [WRN] 127.0.0.1:53185 - mid:21 - "local_1001" - Closing because a remote connection has started with the same client ID: "local_1001"`

**Comment by ysfscream** [comment] 2022-03-08 01:38
@LLLLimbo Sorry about that, I couldn't reproduce this issue. This seems a little strange. But it feels like the connection info data is not updated, maybe you should click Edit and then update the connection to try again.

**Comment by LLLLimbo** [comment] 2022-03-08 02:59
> 

How can I provide more valuable information to assist you in troubleshooting the problem?

**Comment by ysfscream** [comment] 2022-03-08 05:46
@LLLLimbo OK, provide me with every step of the way you create and then connect. Includes detailed steps to modify the client id. Let's see if I can reproduce.

**Comment by LLLLimbo** [comment] 2022-03-08 23:41
> @LLLLimbo OK, provide me with every step of the way you create and then connect. Includes detailed steps to modify the client id. Let's see if I can reproduce.

Here are the steps:
1. Create first connection named `local-leafnode-1`  and connect to mqtt broker
2. Create second connection named `local-cloud-1` and connect to mqtt broker
3. You should see first connection is interrupted, and mqtt broker's logs show there is a client_id conflict.

I exported the configuration files for these two connections from MQTTX
[coinfigs.zip](https://github.com/emqx/MQTTX/files/8210433/coinfigs.zip)

**Comment by ysfscream** [comment] 2022-03-09 01:43
Thank you for the information you have provided.

But after I tested it, both connections were fine and there was no problem sending messages to each other and I used the steps you provided and also used the `configs.zip` you gave.

You can look at what's happening in the MQTTX logs, or check for problems with the MQTT Broker.

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/21299158/157355447-6f3dc69e-3b76-4b45-8fd8-5ab8cc7974ed.png">

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/21299158/157355456-531e1d3b-2a71-4ba1-9615-07522cb699cd.png">

**Comment by LLLLimbo** [comment] 2022-03-09 03:15
> Thank you for the information you have provided.
> 
> But after I tested it, both connections were fine and there was no problem sending messages to each other and I used the steps you provided and also used the `configs.zip` you gave.
> 
> You can look at what's happening in the MQTTX logs, or check for problems with the MQTT Broker.
> 
> <img alt="image" width="1025" src="https://user-images.githubusercontent.com/21299158/157355447-6f3dc69e-3b76-4b45-8fd8-5ab8cc7974ed.png">
> 
> <img alt="image" width="1025" src="https://user-images.githubusercontent.com/21299158/157355456-531e1d3b-2a71-4ba1-9615-07522cb699cd.png">

Thank you for your answer, I have not encountered this problem for the time being after I cleared the data of MQTTX, I will keep an eye on it

**Comment by ysfscream** [comment] 2022-03-09 03:18
OK. However, it may be due to the storage of the client id, if there is still this problem later, please continue to feedback to me.

Thanks for using it.

**Comment by ysfscream** [comment] 2022-06-24 01:20
Hi, if there is no problem, I will close this issue, thanks.

**Closed by ysfscream** 2022-06-24 01:20 UTC
Labels: help wanted, discussion
