### ISSUE TITLE
[Bug] There's nothing displayed on the UI

### ISSUE THREAD

**Issue by terry-xiaoyu** [emqx/MQTTX#1311] opened 2023-05-29 01:28 UTC
#### What did I do

I used it without any issues for the past two days, but yesterday I found that after opening MQTTX (ver: 1.9.3) software, nothing was displayed.

#### Environment

- OS: OS version, e.g. Microsoft Windows 11 Chinese Edition 64bit 10.0.22621
- BuildNumber Caption OSArchitecture Version 22621
- MQTTX version, 1.9.3

#### More detail

no logs

**Comment by ysfscream** [comment] 2023-05-29 06:52
Duplicate of #968

Hi, thanks for your feedback. There could be many reasons you're experiencing this issue, and it could be related to the software itself, its compatibility with your OS, or other factors. Here's what you can try to solve the problem:

1. Always Run MQTTX as an Administrator: Right-click the MQTTX icon, select Properties, then in the Compatibility tab, check "Run this program as an administrator". Click OK to save the settings.
2. Check File Permissions for MQTTX: Check the permissions of relevant files in the installation directory of MQTTX. Ensure your user account has sufficient permissions to access and modify these files.
3. Review your Security Software: Sometimes, antivirus software or firewalls might block certain applications from correctly accessing files or networks. Check your security settings to ensure MQTTX is not being blocked.
4. Delete and Recreate MQTTX Database File: Delete the %USERPROFILE%\AppData\Roaming\MQTTX\MQTTX.db file and restart MQTTX. This will force MQTTX to recreate the .db file which might resolve the issue.
5. Reinstall MQTTX: A simple reinstall might fix potential corruption or file missing issues. Uninstall the application completely, and then download the latest version from the official website. Install it again to see if the problem persists.

**Closed** 2023-07-14 02:59 UTC
Labels: bug, Desktop
