### ISSUE TITLE
wss in 8084 port stop to work with mqttx

### ISSUE THREAD

**Issue by actionoise** [emqx/MQTTX#1733] opened 2024-08-10 17:58 UTC
Hello 

from today the cdn:
https://unpkg.com/mqtt@4.3.7/dist/mqtt.min.js
stop to work with url:

wss://broker.emqx.io:8084/mqtt

i have this error in log :

mqtt.min.js:1 WebSocket connection to 'wss://broker.emqx.io:8084/mqtt' failed: 
qweer.html:61 Client is offline
qweer.html:65 Reconnecting...

thanks in advance for a response.

**Comment by ysfscream** [comment] 2024-08-12 02:08
It looks like this issue is caused by the public broker at [broker.emqx.io](http://broker.emqx.io/). I can't connect to it with wss either. I will contact the maintainer to fix this issue.

**Comment by helpernavisoft** [comment] 2024-08-12 04:04
Strange or coincidence. When this error occurs even with broker installed locally.

**Comment by ysfscream** [comment] 2024-08-12 05:35
@helpernavisoft broker.emqx.io now works for WSS on port 8084. Welcome to try again.

If you are installing locally, you should update the config with the cert files and more for WSS connection. Thanks. I will close this issue.

**Closed by ysfscream** 2024-08-12 05:35 UTC
Labels: bug, EMQX
