### ISSUE TITLE
[Bug] Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by leonardwoo** [emqx/MQTTX#990] opened 2022-07-20 01:59 UTC
See: https://imgur.com/a/38vOmVB

#### Environment

- OS: Windows 10 21H2
- MQTTX CLI version, v1.8.1
- NPM 8.14.0

**Comment by ysfscream** [comment] 2022-07-20 07:34
Hi, welcome to trying the MQTT X CLI, the error is supposed to be unrelated to MQTT X CLI? I'm unsure because the error message is that the localhost address could not be found. ref: https://blog.andrewmmc.com/node-js-error-getaddrinfo-enotfound-localhost-b7ee35e1bb60

**Comment by leonardwoo** [comment] 2022-07-20 10:04
> Hi, welcome to trying the MQTT X CLI, the error is supposed to be unrelated to MQTT X CLI? I'm unsure because the error message is that the localhost address could not be found. ref: https://blog.andrewmmc.com/node-js-error-getaddrinfo-enotfound-localhost-b7ee35e1bb60

That's not it

**Comment by ysfscream** [comment] 2022-07-22 16:55
It recurred when I entered an invalid host address, so I would still recommend that you check that your host address is correct.

<img width="601" alt="image" src="https://user-images.githubusercontent.com/21299158/180487590-a18b54ec-e81a-48cc-9d64-6d4c0aecf4c4.png">

**Comment by leonardwoo** [comment] 2022-07-23 01:32
plz try use emqx-OS in your computer with IP

**Comment by leonardwoo** [comment] 2022-07-23 01:43
When I use another way, still like that.
https://imgur.com/a/sg3RdvX

**Comment by ysfscream** [comment] 2022-07-25 05:38
I have used various methods without reproducing the problem, or maybe I should test it on Windows.

**Comment by ysfscream** [comment] 2022-07-25 05:44
I have used various methods without reproducing the problem, or maybe I should test it on Windows.

**Comment by ysfscream** [comment] 2022-10-12 02:19
Thanks for the feedback, if there are no more issues I will close the issue and welcome you to use https://github.com/emqx/MQTTX/releases/tag/v1.8.3

**Closed by ysfscream** 2022-10-12 02:19 UTC
Labels: help wanted, discussion, CLI

**Comment by alessandrobrugnera** [comment] 2023-11-22 01:56
I solved this by using `-h 127.0.0.1` instead of `-h '127.0.0.1'`. Remove the single quotes also from the topic otherwise it will publish to `'topic'` instead of `topic`. If you need to write a message with spaces inside use double quotes.

**Comment by Red-Asuka** [comment] 2023-11-22 02:06
@alessandrobrugnera I'm glad your problem has been resolved. Using Windows is slightly different from other operating systems. We have added explanations in the document and also welcome you to supplement it. https://mqttx.app/docs/cli/downloading-and-installation#windows
