### ISSUE TITLE
[Bug] mqttx-cli-macos-x64  can't run in macos Sonoma 14.2.1

### ISSUE THREAD

**Issue by littlerokie** [emqx/MQTTX#1706] opened 2024-06-28 03:34 UTC
#### What happened

@~$ ./mqttx-cli-macos-x64 sub -t 'hello' -h 'broke.emqx.io' -p 1883
./mqttx-cli-macos-x64: line 1: syntax error near unexpected token `newline'
./mqttx-cli-macos-x64: line 1: `<?xml version="1.0" encoding="UTF-8"?>'

#### Environment
Intel Core i5
- OS: macos Sonoma 14.2.1
- MQTTX version, v1.10.0

**Comment by ysfscream** [comment] 2024-06-28 06:05
@littlerokie Thank you for your feedback.

We apologize for the inconvenience caused by the missing `mqttx-cli-macos-x64` file. We have now updated the file. Please follow these steps to remove the current MQTTX CLI and reinstall it:

1. Remove the current MQTTX CLI:
   ```bash
   sudo rm -rf /usr/local/bin/mqttx
   ```

2. Download and install the updated version:
   ```bash
   curl -LO https://www.emqx.com/en/downloads/MQTTX/v1.10.0/mqttx-cli-macos-x64
   sudo install ./mqttx-cli-macos-x64 /usr/local/bin/mqttx
   ```

If the issue persists, please install using Homebrew:
```bash
brew install emqx/mqttx/mqttx-cli
```

I have tested this, and it works successfully. We apologize again for any inconvenience caused.

<img width="810" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/1930302d-e19a-41c5-bc2b-b141fea84fa6">

**Comment by ysfscream** [comment] 2024-07-16 09:49
If there is no update, I will close this issue. Thanks.

**Closed by ysfscream** 2024-07-16 09:49 UTC
Labels: bug, CLI
