### ISSUE TITLE
[Bug] Include icons for all sizes in AppImage bundle

### ISSUE THREAD

**Issue by daenney** [emqx/MQTTX#535] opened 2021-03-13 17:55 UTC
#### What did I do

I tried to package the AppImage for AUR.

#### What happened

The icon for MQTTX is missing once the resulting desktop file is installed, causing the generic icon to be shown.

#### Expected

The proper icon is shown.

#### Environment

- OS: Linux (5.11.6)
- MQTTX version: 1.5.2

#### More detail

The AppImage archive only includes an icon in the `0x0` directory:
```
squashfs-root/usr/share
squashfs-root/usr/share/icons
squashfs-root/usr/share/icons/hicolor
squashfs-root/usr/share/icons/hicolor/0x0
squashfs-root/usr/share/icons/hicolor/0x0/apps
squashfs-root/usr/share/icons/hicolor/0x0/apps/mqttx.png
```

This is problematic, as 0x0 icons aren't picked up on by the system. The icon itself however is actually 512x512, and by moving it into `hicolor/512x512/apps` instead everything works fine.

This is an Electron build/package issue most likely: https://www.electron.build/icons#linux. It might require upgrading electron-builder.

**Comment by oceanlvr** [comment] 2021-03-14 09:44
As you said, it might be caused by icon position and electron build, could you please fix it in your environment and tell us the result?
https://github.com/emqx/MQTTX/blob/4c6f34ad3de7b2ee9be2af8d5727e0921f9c4ec3/vue.config.js#L69-L71

maybe we should change this line to `512x512.png` ？

**Comment by ysfscream** [comment] 2023-02-03 07:06
Is this still an issue at the moment? Feel free to use https://github.com/emqx/MQTTX/releases/tag/v1.9.1, I will close the issue first, if it still exists you can reopen it.

**Closed by ysfscream** 2023-02-03 07:06 UTC
Labels: bug, Desktop
