### ISSUE TITLE
[Bug] Very long message gets stuck in the view even if deleted

### ISSUE THREAD

**Issue by afeurra** [emqx/MQTTX#928] opened 2022-04-13 09:21 UTC
#### What did I do

I published a very log message (300KB+) to a topic I was subscribed to. Then I deleted that message from my message list.

#### What happened

The message was deleted and a green Success snacked popped out, but the message stayed in the list. When I try to deleted again I get a red Error snack.

#### Expected

I expected the message to be deleted (which happened) and removed from the list (which didn't happen).

#### Environment

- OS: MacOS 12.2.1 Monterey, Windows 11
- MQTTX version, e.g. v1.7.3

#### More details

I could see that the message was correctly deleted from DB, it just hangs on the view. This happens if I delete the single message (by right-clicking on it) but also if I clear the hole history (by using the context menu). No matter the QoS or the retain flag or the format.
The only way to clear the list is restarting MQTTX.
I cannot post the message here (it comes from an IoT device we are developing) but you can replicate this by simply copying the source code of a Google page.

**Comment by ysfscream** [comment] 2022-04-14 01:36
@afeurra Hi, thanks for your feedback, and there is a duplicate of #922, but it is described in Chinese.

I still can't reproduce it. Could you please provide me with your 300kb+ message and I will try?

**Comment by afeurra** [comment] 2022-04-14 06:51
HI! Sorry I didn't see the issue #922, but Chinese is really bad!

Please take a look at the attached message and follow these steps:

1. connect to any broker (EMQ will not work because it disconnects if you use such a big message; you cloud use test.mosquitto.org)
2. do not subscribe to any topic, we'll use the Sent queue
3. copy-paste the attached file in the write-message textarea
4. choose Plaintext as payload format
5. choose any topic
6. send the message and wait for it to appear in the message list as Sent
7. delete the message from the message list
8. see that it still appears in the list
9. try to delete the message again
10. 
[message.txt](https://github.com/emqx/MQTTX/files/8486884/message.txt)

**Comment by ysfscream** [comment] 2022-04-15 06:25
OK, thanks for your detailed description. I will try it and fix it.

And I translate the Chinese issue.

**Comment by ysfscream** [comment] 2022-06-24 01:13
It's fixed on https://github.com/emqx/MQTTX/releases/tag/v1.8.0, thanks.

**Closed by ysfscream** 2022-06-24 01:13 UTC
Labels: bug
