### ISSUE TITLE
[Bug] When receiving large data, it is now impossible to fold, which used to be foldable.

### ISSUE THREAD

**Issue by DavideYang125** [emqx/MQTTX#1731] opened 2024-08-05 06:51 UTC
If the received message contains a large amount of data, can you fold the data?
It used to fold when it was used, and suddenly it can't fold anymore.

**Comment by ysfscream** [comment] 2024-08-05 08:20
Yes, we have supported the message folding function for big data since version 1.10.0: https://www.emqx.com/en/blog/mqttx-1-10-0-release-notes.

I just tested version 1.10.1 and still did not find any issues.

<img width="497" alt="image" src="https://github.com/user-attachments/assets/2b825863-a965-4afa-8fb4-86987620d1b7">

<img width="679" alt="image" src="https://github.com/user-attachments/assets/2691b83b-7f9a-4a37-a18e-4efddd296f28">

Could you please provide more detailed information? For example, test data samples, etc., so that I can see if I can reproduce the problem.

**Comment by ysfscream** [comment] 2024-08-12 02:26
It's missing more detailed info. I will close this issue for now. If there are any updates, I will reopen it. Thanks.

**Closed by ysfscream** 2024-08-12 02:26 UTC
Labels: bug, discussion, desktop
