### ISSUE TITLE
[Bug] Disconnection when hitting Enter in the subscription modal

### ISSUE THREAD

**Issue by afeurra** [emqx/MQTTX#1297] opened 2023-05-17 09:35 UTC
#### What did I do

When I am subscribing to a topic (or editing a subscription) I often write the topic inside the textarea then I hit Enter (I am used to use my keyboard instead of my mouse).

#### What happened

An "Error: Invalid topic <the topic with a blank char where the Enter was hit> " appears. The client is automatically disconnected.

#### Expected

A  would expect the modal to behave as if I hit the Confirm button. Most of all, I expect the client to NOT disconnect.

#### Environment

- OS: Windows 11
- v1.9.2

#### More detail

This behaviour also causes another sub-issue: when the client disconnects, the subscription modal is still open so I can try to subscribe to a topic while disconnected from broker. When I do, the subscription fails (of course) but the Confirm button remains in the pending state (I mean I still see the spinner spinning) and there is no way to exit this state unless I restart the app. Again, this second issue could be avoided by fixing the main one, but I would suggest to reset the state of the Confirm button when the modal is closed.

**Comment by ysfscream** [comment] 2023-05-18 01:45
Hello! I tried to simulate this issue but couldn't reproduce your described problem. I'm sorry for the inconvenience.
Could you provide more details about what you entered for the topic and subscription? Any additional information would be greatly appreciated to understand better and fix this issue. Thank you for your patience and support!

**Comment by afeurra** [comment] 2023-05-19 07:20
Hi! I tried to reproduce the issue too using a couple of free live demo, including broker.emqx.io and test.mosquitto.org and I can confirm that the issue does not happen with those. It appears with 3 brokers of mine which are all mosquitto's and they all use TLS with self-signed authentication and ACL's that could actually deny the client to connect to "weird" topics. I'm adding more info and screenshots.
First screenshot: config. Client is not connected yet.
<img width="1440" alt="screen1" src="https://github.com/emqx/MQTTX/assets/47101794/cba96629-8281-47c0-9497-c5be78084ab3">
Second screenshot: subscription, client is connected already. Please see the position of the mouse cursor in the textarea, I'm hitting the Enter key next.
![screen2](https://github.com/emqx/MQTTX/assets/47101794/886d8332-4c39-44a6-a62f-1ccdd8c4d446)
Third screenshot: disconnection. In the text area I an clear see a break line char, which is not a valid character for a topic. The client is disconnected already, which now I suppose it could be because of the broker dropping the connection because of the bad subscription. Please see that I can still it the Confirm button, which I'll do in the next screenshot.
![screen3](https://github.com/emqx/MQTTX/assets/47101794/1832ba61-859b-4c1a-80f5-df0a92503cea)
Forth screenshot: clicking Confirm when client is disconnected. Spinner is stuck at spinning.
<img width="1440" alt="screen4" src="https://github.com/emqx/MQTTX/assets/47101794/851e984a-17ed-451f-951a-4360608728fb">

**Comment by ysfscream** [comment] 2023-05-22 10:11
Based on your description, the issue relates to the client attempting to subscribe to a topic with a newline character. MQTTX may not be the primary cause of the issue, especially given that other brokers you have tested do not exhibit the same problem. The issue could be specifically related to your Mosquito brokers' configuration, particularly regarding handling topics with invalid characters.

I would suggest reviewing your ACL configurations or testing with ACL validation turned off. You could also investigate what action is being taken during topic validation.

Checking the logs for any relevant information when the disconnection happens might be helpful too. 


Nonetheless, please do not hesitate to share if you encounter any irregularities with MQTTX or have any further concerns. We are here to help and continuously seek ways to improve our software.

**Comment by ysfscream** [comment] 2024-02-19 09:05
If the issue doesn't recur, I'll close it. Thanks for your usage.

**Closed by ysfscream** 2024-02-19 09:05 UTC
Labels: bug, discussion, desktop
