### ISSUE TITLE
[Feature] protobuf support

### ISSUE THREAD

**Issue by Chordp** [emqx/MQTTX#1243] opened 2023-02-28 11:00 UTC
#### Motivation

protobuf support

**Comment by ysfscream** [comment] 2023-03-01 02:50
Thanks! Duplicate of #555

**Comment by ysfscream** [comment] 2023-07-14 01:49
Hi! Thank you for your feedback. Currently, we have added support for it in https://github.com/emqx/MQTTX/releases/tag/v1.9.4.

**Closed by ysfscream** 2023-07-14 01:49 UTC
Labels: feature, CLI, Web, Desktop
