### ISSUE TITLE
[Bug] Duplicated received messages appear in a subscription

### ISSUE THREAD

**Issue by HamzaHajeir** [emqx/MQTTX#1372] opened 2023-07-26 15:20 UTC
#### What did I do

In my MQTT tests, I'm subscribing to local mosquitto to multiple topics, one topic with a wildcard (#), another with (test) topic.

#### What happened

When browsing (test) subscription, each of the publishes to (test) appears duplicated.

The issue exists even if explicitly setting Subscription ID for the (test) topic.

#### Expected

Only one appearance per publish.

#### Environment

- Windows 11
- MQTTX version, e.g. v1.9.4

#### More detail

It happens also for subscribing a shared topic, it appears to receiving all related publishes from (#) subscription.

![image](https://github.com/emqx/MQTTX/assets/32960423/eafe856b-48dd-4b49-8078-c354c4f668f2)

**Comment by ysfscream** [comment] 2023-07-27 08:35
@HamzaHajeir Hi, thanks for your use. And the duplication of messages you are observing when subscribing to both wildcard and exact topics is expected behavior.

The way received messages are handled for overlapping subscriptions depends on the specific MQTT broker implementation. The broker can send one message per subscription or only one for overlapping subscriptions.

EMQX will send a separate message for each matching subscription, so you see duplicate messages in this case.

I would recommend being aware of the difference in behavior when using wildcard and exact topic subscriptions since different brokers handle this differently.

**Comment by HamzaHajeir** [comment] 2023-07-27 09:45
Thank you for the explanation.

So it's the server which sends a duplicate message normally?


But I'm not sure if it's a correct behavior of managing Subscription
ID-based subscriptions.

As the MQTT server will send only a copy to the wildcard subscription, but
won't mean to deliver to other subscription-id based subscriptions.

It's vital for such shared topics using a subscription id, as the server
will send to such subscriptions only in turn.

**Comment by ysfscream** [comment] 2023-07-28 02:48
Yes, subscription identifiers help differentiate overlapping subscription messages, but additional client logic is required to suppress duplicates.

The MQTT server sending duplicates is normal behavior, not a result of subscription identifiers.

The purpose of subscription identifiers is to differentiate overlapping subscription messages, not prevent duplicate sends.

Servers may still send duplicate messages for overlapping subscriptions with identifiers. This depends on implementation.

Subscription identifiers don't guarantee single message copies for wildcard subscriptions. Avoiding duplicates needs special server handling.

MQTTX receives duplicates from different identifiers, helping users understand message sources.

<img width="1137" alt="image" src="https://github.com/emqx/MQTTX/assets/21299158/26ae2abf-8154-4c7c-b30c-81f87f88492a">

**Comment by HamzaHajeir** [comment] 2023-07-28 09:23
Of course the subscription id won't change the server-side handling. 
But if a received message holds a subscription id, then it should be directed to its subscription. 
Otherwise the subscription shall not receive messages not holding its subscription id.
From MQTT v5.0 specification:

> Non-normative comment
> Usage scenarios, for illustration of Subscription Identifiers.
> ·         The Client implementation indicates via its programming interface that a publication matched more than one subscription. The Client implementation generates a new identifier each time a subscription is made. If the returned publication carries more than one Subscription Identifier, then the publication matched more than one subscription.
> 
> ·         The Client implementation allows the subscriber to direct messages to a callback associated with the subscription. The Client implementation generates an identifier which uniquely maps the identifier to the callback. When a publication is received it uses the Subscription Identifier to determine which callback is driven.
> 
> ·         The Client implementation returns the topic string used to make the subscription to the application when it delivers the published message. To achieve this the Client generates an identifier which uniquely identifies the Topic Filter. When a publication is received the Client implementation uses the identifiers to look up the original Topic Filters and return them to the Client application.
> 
> ·         A gateway forwards publications received from a Server to Clients that have made subscriptions to the gateway. The gateway implementation maintains a map of each unique Topic Filter it receives to the set of ClientID, Subscription Identifier pairs that it also received. It generates a unique identifier for each Topic Filter that it forwards to the Server. When a publication is received, the gateway uses the Subscription Identifiers it received from the Server to look up the Client Identifier, Subscription Identifier pairs associated with them. It adds these to the PUBLISH packets it sends to the Clients. If the upstream Server sent multiple PUBLISH packets because the message matched multiple subscriptions, then this behavior is mirrored to the Clients.

It does describe more than one Subscription ID - based subscription, but we can derive a simplified case, with just a single one.

> The Client implementation allows the subscriber to direct messages to a callback associated with the subscription. The Client implementation generates an identifier which uniquely maps the identifier to the callback. When a publication is received it uses the Subscription Identifier to determine which callback is driven.


Let callback = Topic Subscription in MQTTX, then why does it receive other than its specified Subscription ID-publishes?

If receiving only relevant publishes is not the behavior, then why does the Subscription ID field exist?

**Comment by tigercl** [comment] 2023-07-31 03:18
Hello, I think you have not received the unexpected publication content, because `testtopic/test` and `testtopic/#` are your subscriptions, when you publish a message to the topic `testtopic/test`, MQTT Broker will find that this message matches two of your subscriptions.

According to the protocol specification, at this time, MQTT Broker can forward the message for each of the two subscriptions, or only forward the message once, which depends entirely on the choice of MQTT Broker. And EMQX is the former.

When you use subscription identifiers, implementations that forward the message for each matching subscription will include the corresponding subscription identifier in the message to indicate to the client which subscription the message came from. Whereas an implementation that only forwards the message once for all matching subscriptions will include all subscription identifiers in the message, you will see multiple subscription identifiers in the received message.

**Comment by ysfscream** [comment] 2023-09-15 15:41
If there are no other concerns, I will temporarily close this issue. Thank you for using MQTTX.

**Closed by ysfscream** 2023-09-15 15:41 UTC
Labels: wontfix, discussion, desktop
