### ISSUE TITLE
[Bug] MQTT connection failing with Self signed certificates

### ISSUE THREAD

**Issue by farrukh-dplit** [emqx/MQTTX#1041] opened 2022-08-10 08:59 UTC
#### What did I do

tried same setup that is functional for 1.8.0, selected self signed cert options and added certificates/private key.

#### What happened

connection failed, tried on two different machines

#### Expected

connection should be open, just verified from version 1.8.0

#### Environment

- OS: ubuntu 18.04, 20.04, 22.04
- MQTTX version v1.8.2

**Comment by ysfscream** [comment] 2022-08-11 02:00
Hi, thanks for your feedback. But could you please tell me if there are any error messages or logs? Maybe also check the MQTT Broker logs, I can't be sure what the issue is with the current information provided.

**Comment by farrukh-dplit** [comment] 2022-08-12 16:01
![image](https://user-images.githubusercontent.com/110097439/184395873-3a39929d-20f9-47c7-8b71-28ada638f83e.png)
![image](https://user-images.githubusercontent.com/110097439/184395976-c0b1ea55-c61a-4ea7-9517-4349fae7967a.png)

same setup tested on 1.8.0 and is functional, no such logs there.

**Comment by farrukh-dplit** [comment] 2022-08-12 16:05
these logs are from 1.8.2, where connection never open,
same setup tested on 1.8.0 and is functional, no such logs there.
![image](https://user-images.githubusercontent.com/110097439/184396543-46098b53-c69f-4d4f-8732-7acee1121bf2.png)
![image](https://user-images.githubusercontent.com/110097439/184396608-ab473169-ea27-42f1-8ae5-fbff0e4b37d0.png)

**Comment by ysfscream** [comment] 2022-08-15 02:28
Oh, thanks. This does not appear to be any trace to the error log, indicating that the probability may be a problem with your server-side authentication, when the certificate or server configuration error, you can check the error log of the MQTT service, generally, this time may be the service terminated the connection.

It is recommended to use a packet analyzer to analyze what is happening when connecting, if it is an [RST] error, it is probably a TLS parsing failure

**Comment by farrukh-dplit** [comment] 2022-08-15 05:33
Is authentication method 'null' normal here?
also after I installed 1.8.0 on top of 1.8.2, the mqtt profile that I previously created in version 1.8.2 wasn't opening in 1.8.0 as well, but a new MQTT connection profile with same certificates and settings created in 1.8.0 is opening fine.

**Comment by ysfscream** [comment] 2024-02-19 08:57
The certificate issue is running well in the latest version, 1.9.9. I am not sure if the issue still exists. If there are any new practical problems, please feel free to resubmit the issue. I will close this one.

**Closed by ysfscream** 2024-02-19 08:57 UTC
Labels: bug, help wanted, discussion, desktop
