### ISSUE TITLE
1.4.0版本有bug, 只能连接本机的mqtt服务器.

### ISSUE THREAD

**Issue by jinyanhui2008** [emqx/MQTTX#382] opened 2020-11-27 02:57 UTC
配置其他地址的服务器也会只连接127.0.0.1:1883端口.

**Comment by ysfscream** [comment] 2020-11-27 07:16
Duplicate of #355

**Comment by ysfscream** [comment] 2020-11-30 01:36
It has been fixed in [v1.4.1](https://github.com/emqx/MQTTX/releases/tag/v1.4.1), I will close this issue

**Closed by ysfscream** 2020-11-30 01:36 UTC
Labels: bug
