### ISSUE TITLE
[Bug] MQTTX V1.9.0 does not run in centos7.7

### ISSUE THREAD

**Issue by xiaoxiao8508** [emqx/MQTTX#1139] opened 2022-11-09 06:40 UTC
#### What did I do

正常运行程序

#### What happened

运行报错

#### Expected
[root@dcamp ~]# sudo install ./mqttx-cli-linux-x64 /usr/local/bin/mqttx
[root@dcamp ~]# mqttx
/usr/local/bin/mqttx: line 1: syntax error near unexpected token `newline'
/usr/local/bin/mqttx: line 1: `<!doctype html>'
#### Environment

- OS: Centos 7.7 
- MQTTX V1.9.0, e.g. v1.5.0

#### More detail

V1.8.0正常运行

**Comment by Red-Asuka** [comment] 2022-11-11 02:58
This is caused by uploaded incorrect resources, it has been fixed, you can try to download and install again.

**Comment by ysfscream** [comment] 2022-11-13 13:37
Thanks for your feedback! I will close the issue.

**Closed by ysfscream** 2022-11-13 13:37 UTC
Labels: bug, CLI
