### ISSUE TITLE
[Bug] Pop-up error window when closing MQTTX

### ISSUE THREAD

**Issue by liux-pro** [emqx/MQTTX#1558] opened 2024-01-12 05:08 UTC
#### What did I do

Click on "New Connection," then close MQTTX directly; an error will pop up.

![recording](https://github.com/emqx/MQTTX/assets/20764978/b04b7107-c329-4e7e-a54b-be14391c8298)

#### What happened

Get an error.

#### Environment

- OS: OS version, Window 10
- MQTTX version, v1.9.8

#### More detail

More detail include `log` information or screenshot

**Comment by ysfscream** [comment] 2024-01-16 09:55
Hi @liux-pro,

First of all, my apologies for the delayed response to your issue. Thank you for reporting the bug where an error pop-up appears when closing MQTTX after clicking "New Connection."

I have attempted to replicate the issue on my end, but so far, I haven't been able to reproduce it on my macOS system. This may be a problem specific to Windows 10. To better understand and address this issue, please provide more details, such as the error message you're receiving and any relevant log information or screenshots. This additional information would be beneficial for our troubleshooting process.

**Comment by ni00** [comment] 2024-01-29 04:13
Hi @ysfscream , I tested this bug on Windows 11 and was unable to reproduce it. I suspect it's an issue specific to Windows 10.

**Comment by ysfscream** [comment] 2024-01-31 06:10
@ni00 Thanks for your testing and feedback!

**Comment by ysfscream** [comment] 2024-02-21 02:29
Looks like the MQTTX doesn't cause it. I will close this issue, and if new bugs are reproducible, I will reopen it.

Thanks for your support @ni00

**Closed by ysfscream** 2024-02-21 02:29 UTC
Labels: bug, desktop, Windows
