### ISSUE TITLE
[Bug] the title of bug report

### ISSUE THREAD

**Issue by bambuo** [emqx/MQTTX#1518] opened 2023-12-08 03:53 UTC
#### What did I do

向一个配置了 SSL 连接认证的 MQTT 进行连接

#### What happened

MQTTX 无法正确连接

#### Expected

正确情况下是能正常连接成功的

#### Environment

- OS: Linux Mint LMDE 6 Faye
- MQTTX v1.9.6

#### More detail

相同的配置连接相同的 MQTT 时，MQTT.fx v1.7.1 能正常连接成功，而 MQTTX v1.9.6 却无法连接，在配置中所见，有一个区别就是 MQTT.fx 有一个 PEM Formatted 的勾选
![2023-12-08_11-48](https://github.com/emqx/MQTTX/assets/44076708/b049f703-5741-48d7-90e0-5a555cf57b56)
![2023-12-08_11-49](https://github.com/emqx/MQTTX/assets/44076708/69c4c8b6-64a9-4a1b-9127-d2da29a6cd84)
![2023-12-08_11-50](https://github.com/emqx/MQTTX/assets/44076708/8e09867c-679d-4e4d-b4ba-a0ee9dccbe1c)
![2023-12-08_11-50_1](https://github.com/emqx/MQTTX/assets/44076708/73892d02-ee24-4375-8208-3d964b3d1c92)

**Comment by ysfscream** [comment] 2023-12-08 09:50
Hi @rribons, It appears there's an issue with the TLS certificate's altnames, not including the specified IP address. And it seems this issue is a duplicate of https://github.com/emqx/MQTTX/issues/573, #1456 and  I recommend referring to [this comment](https://github.com/emqx/MQTTX/issues/573#issuecomment-1774359646) for more insights.

**Closed by ysfscream** 2023-12-08 09:50 UTC
Labels: bug
