### ISSUE TITLE
[Bug] Subscribing to # hangs the app

### ISSUE THREAD

**Issue by daenney** [emqx/MQTTX#533] opened 2021-03-13 17:42 UTC
#### What did I do

Created a subscription for `#`

#### What happened

The application slowed down, everything started to stutter. UI became completely unresponsive, the disconnect button wouldn't work. Had to forcefully kill the app, which resulted in a corrupted `db.json` causing the app to refuse to start up.

#### Expected

The application remains functional and responsive

#### Environment

- OS: Linux (5.11.6)
- MQTTX version: v1.5.2

**Comment by oceanlvr** [comment] 2021-03-14 08:43
@daenney Thanks for your support, could you tell us your `MQTT broker` environment and log after your operation?

**Comment by daenney** [comment] 2021-03-14 16:40
My broker is emqx 4.2.7.

I don’t know what you mean with “ environment and log after your operation?”. Do you want to see any logs emqx generated after I used mqttx to subscribe?

**Comment by oceanlvr** [comment] 2021-03-14 16:49
> My broker is emqx 4.2.7.
> 
> 
> 
> I don’t know what you mean with “ environment and log after your operation?”. Do you want to see any logs emqx generated after I used mqttx to subscribe?

Yes, more details plz. I can't reproduce.
emqx reject # topic by default, could you please check the emqx acl.conf configure file?

**Comment by ysfscream** [comment] 2021-03-15 01:31
It may be an issue similar to this one. #457

@oceanlvr Is caused by the amount of received messages.

**Comment by oceanlvr** [comment] 2021-03-15 01:51
Ok, maybe we should fix the read/write problem in a better way.

**Comment by daenney** [comment] 2021-03-15 12:26
On the ACL thing, I explicitly have `{allow, all, subscribe, ["$SYS/#", {eq, "#"}]}.` on this cluster since this is my testing rig. But yes, the problem isn't so much the subscription as the amount of messages flowing through it. It seems to cause the UI to be permanently catching up/processing a backlog of events.

#457 sounds similar, though in my particular case it's MQTT 3.1.1 and all messages are strings.

**Comment by Tazintosh** [comment] 2022-11-04 11:39
Not sure the issue is fixed. At least, I'm running v1.8.3 and for some reason, got the history filled with more than 44000 entries. Now the MQTTX.db weight 14MB (only), and the app is absolutely unusable. It's so unresponsive that it will disconnect before I can clear the history. BTW, clearing while disconnected won't work.
My only workaround is to delete MQTTX.db and start from scratch, not cool :(

**Comment by ysfscream** [comment] 2022-11-07 01:27
@Tazintosh Hi, thanks for the feedback. YES, It's true that this has been an issue, and we haven't optimized it for a large number of messages, but we're actually keeping an eye on it, and it's actually affecting the MQTT X experience, so I'm going to reference your comments and create a new issue until it's fixed.

**Comment by LucidEye** [comment] 2022-12-10 19:32
Hello, I am having this problem as well.  The history is filling up with messages and causes the app to become completely unresponsive. EXTREMELY frustrating since this is the very first time I'm using the app... it does not instill a lot of confidence in your product. This seems to be happening even when the app is shut down?  I had over 5000 messages in the history when I tried to open the app this morning.
I don't understand this behavior since I have all of the QOS settings on the publisher to 0... which means that there should be no messages being retained, right?  So why does it retain these messages in the history?  It should print the latest message, and then discard it when the next message is received, right?
Is there some way we can limit the max number of messages retained in the history buffer to prevent it from eating up all the memory in my system? Maybe limit it to the past 50-100 messages or so?  Is there a way to set it so there is no history?  I am only interested in the latest message, I have no need to retain any previous messages.

**Comment by ysfscream** [comment] 2022-12-12 07:19
@LucidEye Hi again. Looks like a good suggestion for store messages. We consider this and improve this part for your need. I will reopen this issue unit this bug has been fixed now.

**Comment by ysfscream** [comment] 2023-02-03 06:52
Apologies for the long wait, welcome to https://github.com/emqx/MQTTX/releases/tag/v1.9.1, that should solve the problem and I will close this issue.

**Closed by ysfscream** 2023-02-03 06:52 UTC
Labels: bug, Desktop
