### ISSUE TITLE
[Bug] wrong username/pawword keeps try to connect even after i have changed it to correctly one

### ISSUE THREAD

**Issue by blankhang** [emqx/MQTTX#1680] opened 2024-06-03 11:31 UTC
#### What did I do

"After using the wrong username or password to connect to the MQTT server, even if I modify to the correct username and password, Mqttx still tries to connect to the MQTT server using the old information. Even if I delete all connection configurations, it still persists in attempting to connect!"

#### What happened
keep saying
Error: Connection refused: Bad username or password

#### Expected

DO NOT auto trying to get a Connection after i changed the info unless i click connection button.
and delete all connection configurations not help at all.

#### Environment

- OS: 14.5
- MQTTX: v1.9.10

#### More detail

More detail include `log` information or screenshot

```log
[2024-06-03 17:29:31] [INFO] MQTTX Desktop App init
[2024-06-03 17:30:16] [INFO] Created for the first time: dev, ID: f2724c70-ea52-421a-8ccf-c668e867f7cd
[2024-06-03 17:30:16] [INFO] Assigned ID f2724c70-ea52-421a-8ccf-c668e867f7cd to MQTTX client
[2024-06-03 17:30:16] [INFO] Client dev connected using MQTT/TCP connection at mqtt://localhost:1883
[2024-06-03 17:30:26] [INFO] The connection dev (clientID mqttx_blank) is offline. MQTT.js onOffline trigger
[2024-06-03 17:30:26] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:30:30] [INFO] Retrying connection for dev, attempt: 0
[2024-06-03 17:30:40] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:30:42] [WARN] MQTTX force stopped reconnecting for dev (Client ID: mqttx_blank)
[2024-06-03 17:30:42] [WARN] MQTTX force closed the connection dev (Client ID: mqttx_blank)
[2024-06-03 17:30:59] [INFO] Connection dev was edited, ID: f2724c70-ea52-421a-8ccf-c668e867f7cd
[2024-06-03 17:31:00] [INFO] Assigned ID f2724c70-ea52-421a-8ccf-c668e867f7cd to MQTTX client
[2024-06-03 17:31:00] [INFO] Client dev connected using MQTT/TCP connection at mqtt://localhost:1883
[2024-06-03 17:31:10] [INFO] The connection dev (clientID mqttx_blank) is offline. MQTT.js onOffline trigger
[2024-06-03 17:31:10] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:31:11] [INFO] Assigned ID f2724c70-ea52-421a-8ccf-c668e867f7cd to MQTTX client
[2024-06-03 17:31:11] [INFO] Client dev connected using MQTT/TCP connection at mqtt://localhost:1883
[2024-06-03 17:31:14] [INFO] Retrying connection for dev, attempt: 0
[2024-06-03 17:31:21] [INFO] The connection dev (clientID mqttx_blank) is offline. MQTT.js onOffline trigger
[2024-06-03 17:31:21] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:31:24] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:31:25] [INFO] Retrying connection for dev, attempt: 1
[2024-06-03 17:31:28] [INFO] Retrying connection for dev, attempt: 2
[2024-06-03 17:31:35] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:31:38] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:31:39] [INFO] Retrying connection for dev, attempt: 3
[2024-06-03 17:31:42] [INFO] Retrying connection for dev, attempt: 4
[2024-06-03 17:31:47] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:31:48] [WARN] MQTTX force stopped reconnecting for dev (Client ID: mqttx_blank)
[2024-06-03 17:31:48] [WARN] MQTTX force closed the connection dev (Client ID: mqttx_blank)
[2024-06-03 17:31:50] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:31:54] [INFO] Retrying connection for dev, attempt: 0
[2024-06-03 17:32:04] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:32:08] [INFO] Retrying connection for dev, attempt: 1
[2024-06-03 17:32:12] [INFO] Connection dev was edited, ID: f2724c70-ea52-421a-8ccf-c668e867f7cd
[2024-06-03 17:32:17] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:32:18] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:32:20] [INFO] Assigned ID f2724c70-ea52-421a-8ccf-c668e867f7cd to MQTTX client
[2024-06-03 17:32:20] [INFO] Client dev connected using MQTT/TCP connection at mqtt://localhost:1883
[2024-06-03 17:32:22] [INFO] Retrying connection for dev, attempt: 2
[2024-06-03 17:32:29] [INFO] Successful connection for dev, MQTT.js onConnect trigger
[2024-06-03 17:32:32] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:32:36] [INFO] Retrying connection for dev, attempt: 3
[2024-06-03 17:32:46] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:32:50] [INFO] Retrying connection for dev, attempt: 4
[2024-06-03 17:33:00] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:33:04] [INFO] Retrying connection for dev, attempt: 5
[2024-06-03 17:33:14] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:33:18] [INFO] Retrying connection for dev, attempt: 6
[2024-06-03 17:33:28] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:33:32] [INFO] Retrying connection for dev, attempt: 7
[2024-06-03 17:33:42] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:33:46] [INFO] Retrying connection for dev, attempt: 8
[2024-06-03 17:33:56] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:34:00] [INFO] Retrying connection for dev, attempt: 9
[2024-06-03 17:34:10] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:34:14] [INFO] Retrying connection for dev, attempt: 10
[2024-06-03 17:34:24] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:34:28] [WARN] Max reconnect limit reached, stopping retries
[2024-06-03 17:34:28] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:34:28] [WARN] MQTTX force closed the connection dev (Client ID: mqttx_blank)
[2024-06-03 17:34:38] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:34:42] [INFO] Retrying connection for dev, attempt: 0
[2024-06-03 17:34:52] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:34:56] [INFO] Retrying connection for dev, attempt: 1
[2024-06-03 17:34:56] [INFO] Connection dev was edited, ID: f2724c70-ea52-421a-8ccf-c668e867f7cd
[2024-06-03 17:35:06] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:35:10] [INFO] Retrying connection for dev, attempt: 2
[2024-06-03 17:35:20] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:20] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:35:24] [INFO] Retrying connection for dev, attempt: 3
[2024-06-03 17:35:26] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:26] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:26] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:27] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:28] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:29] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:32] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:32] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:32] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:33] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:33] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:33] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:33] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:33] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:33] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:34] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:34] [INFO] Cancelled connection for MQTTX client named dev
[2024-06-03 17:35:34] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:35:38] [INFO] Retrying connection for dev, attempt: 4
[2024-06-03 17:35:45] [INFO] Connection dev was edited, ID: f2724c70-ea52-421a-8ccf-c668e867f7cd
[2024-06-03 17:35:48] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:35:52] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:35:56] [ERROR] Connection for dev failed, MQTT.js onError trigger, Error: Error: connect ECONNREFUSED 127.0.0.1:1883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2024-06-03 17:35:56] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:36:00] [ERROR] Connection for dev failed, MQTT.js onError trigger, Error: Error: connect ECONNREFUSED 127.0.0.1:1883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2024-06-03 17:36:00] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 17:36:05] [INFO] Successful connection for dev, MQTT.js onConnect trigger
[2024-06-03 17:36:26] [INFO] Assigned ID f2724c70-ea52-421a-8ccf-c668e867f7cd to MQTTX client
[2024-06-03 17:36:26] [INFO] Client dev connected using MQTT/TCP connection at mqtt://localhost:1883
[2024-06-03 17:36:26] [INFO] Successful connection for dev, MQTT.js onConnect trigger
[2024-06-03 17:36:39] [INFO] Duplicated dev as dev_copy
[2024-06-03 17:36:45] [INFO] Assigned ID 122480d7-1da4-4fc1-a26c-f32f96b30b16 to MQTTX client
[2024-06-03 17:36:45] [INFO] Client dev_copy connected using MQTT/TCP connection at mqtt://localhost:1883
[2024-06-03 17:36:45] [ERROR] Connection for dev_copy failed, MQTT.js onError trigger, Error: Error: Connection refused: Bad username or password
    at MqttClient._handleConnack (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:1388:17)
    at MqttClient._handlePacket (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:549:12)
    at work (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:438:12)
    at Writable.writable._write (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:452:5)
    at doWrite (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (internal/streams/readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[2024-06-03 17:36:45] [WARN] MQTTX force closed the connection dev_copy (Client ID: mqttx_16a41dae)
[2024-06-03 17:36:46] [INFO] Connection for dev_copy closed, MQTT.js onClose trigger
[2024-06-03 18:12:57] [INFO] Connection for dev_copy closed, MQTT.js onClose trigger
[2024-06-03 18:13:37] [INFO] The connection dev (clientID mqttx_blank) is offline. MQTT.js onOffline trigger
[2024-06-03 18:13:37] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 18:13:42] [INFO] Successful connection for dev, MQTT.js onConnect trigger
[2024-06-03 18:20:01] [INFO] Assigned ID f2724c70-ea52-421a-8ccf-c668e867f7cd to MQTTX client
[2024-06-03 18:20:01] [INFO] Client dev connected using MQTT/TCP connection at mqtt://localhost:1883
[2024-06-03 18:20:01] [INFO] Successful connection for dev, MQTT.js onConnect trigger
[2024-06-03 18:20:16] [INFO] Message with payload "{\n  \"msg\": \"hello\"\n}" was successfully published to topic "/test" by dev
[2024-06-03 18:21:33] [INFO] Message with payload "{\n  \"msg\": \"hello\"\n}" was successfully published to topic "/test" by dev
[2024-06-03 18:27:48] [INFO] The connection dev (clientID mqttx_blank) is offline. MQTT.js onOffline trigger
[2024-06-03 18:27:48] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 18:27:48] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 18:27:52] [INFO] Successful connection for dev, MQTT.js onConnect trigger
[2024-06-03 18:28:25] [INFO] Assigned ID f2724c70-ea52-421a-8ccf-c668e867f7cd to MQTTX client
[2024-06-03 18:28:25] [INFO] Client dev connected using MQTT/TCP connection at mqtt://localhost:1883
[2024-06-03 18:28:26] [INFO] Successful connection for dev, MQTT.js onConnect trigger
[2024-06-03 18:28:28] [INFO] Message with payload "{\n  \"msg\": \"hello\"\n}" was successfully published to topic "/test" by dev
[2024-06-03 18:29:14] [INFO] Saved topic: testtopic
[2024-06-03 18:29:14] [INFO] Successfully subscribed to topic: testtopic
[2024-06-03 18:29:23] [INFO] Removed topic: testtopic
[2024-06-03 18:29:23] [INFO] Unsubscribe topic: testtopic
[2024-06-03 18:29:23] [INFO] Saved topic: testtopic/#
[2024-06-03 18:29:23] [INFO] Successfully subscribed to topic: testtopic/#
[2024-06-03 18:29:45] [INFO] Removed topic: testtopic/#
[2024-06-03 18:29:45] [INFO] Unsubscribe topic: testtopic/#
[2024-06-03 18:29:45] [INFO] Saved topic: device
[2024-06-03 18:29:45] [INFO] Successfully subscribed to topic: device
[2024-06-03 18:29:53] [INFO] Removed topic: device
[2024-06-03 18:29:53] [INFO] Unsubscribe topic: device
[2024-06-03 18:29:53] [INFO] Saved topic: deviceLogin
[2024-06-03 18:29:53] [INFO] Successfully subscribed to topic: deviceLogin
[2024-06-03 18:30:00] [INFO] Removed topic: deviceLogin
[2024-06-03 18:30:00] [INFO] Unsubscribe topic: deviceLogin
[2024-06-03 18:30:00] [INFO] Saved topic: deviceLoginStatus
[2024-06-03 18:30:00] [INFO] Successfully subscribed to topic: deviceLoginStatus
[2024-06-03 18:37:48] [INFO] The connection dev (clientID mqttx_blank) is offline. MQTT.js onOffline trigger
[2024-06-03 18:37:48] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 18:37:48] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 18:37:53] [INFO] Successful connection for dev, MQTT.js onConnect trigger
[2024-06-03 18:43:56] [INFO] The connection dev (clientID mqttx_blank) is offline. MQTT.js onOffline trigger
[2024-06-03 18:43:56] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 18:44:01] [INFO] Successful connection for dev, MQTT.js onConnect trigger
[2024-06-03 18:50:11] [INFO] The connection dev (clientID mqttx_blank) is offline. MQTT.js onOffline trigger
[2024-06-03 18:50:11] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 18:50:16] [INFO] Successful connection for dev, MQTT.js onConnect trigger
[2024-06-03 18:59:35] [INFO] Assigned ID f2724c70-ea52-421a-8ccf-c668e867f7cd to MQTTX client
[2024-06-03 18:59:35] [INFO] Client dev connected using MQTT/TCP connection at mqtt://localhost:1883
[2024-06-03 18:59:35] [INFO] Successful connection for dev, MQTT.js onConnect trigger
[2024-06-03 18:59:35] [INFO] Resubscription in progress for topic: deviceLoginStatus
[2024-06-03 18:59:35] [INFO] Saved topic: deviceLoginStatus
[2024-06-03 18:59:35] [INFO] Successfully subscribed to topic: deviceLoginStatus
[2024-06-03 19:07:10] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 19:07:51] [INFO] The connection dev (clientID mqttx_blank) is offline. MQTT.js onOffline trigger
[2024-06-03 19:07:51] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 19:07:56] [INFO] Successful connection for dev, MQTT.js onConnect trigger
[2024-06-03 19:13:59] [INFO] The connection dev (clientID mqttx_blank) is offline. MQTT.js onOffline trigger
[2024-06-03 19:13:59] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 19:14:04] [ERROR] Connection for dev failed, MQTT.js onError trigger, Error: Error: Connection refused: Bad username or password
    at MqttClient._handleConnack (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:1388:17)
    at MqttClient._handlePacket (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:549:12)
    at work (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:438:12)
    at Writable.writable._write (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:452:5)
    at doWrite (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (internal/streams/readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[2024-06-03 19:14:04] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 19:14:09] [ERROR] Connection for dev failed, MQTT.js onError trigger, Error: Error: Connection refused: Bad username or password
    at MqttClient._handleConnack (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:1388:17)
    at MqttClient._handlePacket (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:549:12)
    at work (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:438:12)
    at Writable.writable._write (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:452:5)
    at doWrite (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (internal/streams/readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[2024-06-03 19:14:09] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 19:14:14] [ERROR] Connection for dev failed, MQTT.js onError trigger, Error: Error: Connection refused: Bad username or password
    at MqttClient._handleConnack (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:1388:17)
    at MqttClient._handlePacket (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:549:12)
    at work (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:438:12)
    at Writable.writable._write (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:452:5)
    at doWrite (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (internal/streams/readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[2024-06-03 19:14:14] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 19:14:19] [ERROR] Connection for dev failed, MQTT.js onError trigger, Error: Error: Connection refused: Bad username or password
    at MqttClient._handleConnack (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:1388:17)
    at MqttClient._handlePacket (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:549:12)
    at work (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:438:12)
    at Writable.writable._write (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:452:5)
    at doWrite (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (internal/streams/readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[2024-06-03 19:14:19] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 19:14:24] [ERROR] Connection for dev failed, MQTT.js onError trigger, Error: Error: Connection refused: Bad username or password
    at MqttClient._handleConnack (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:1388:17)
    at MqttClient._handlePacket (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:549:12)
    at work (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:438:12)
    at Writable.writable._write (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/lib/client.js:452:5)
    at doWrite (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/Applications/MQTTX.app/Contents/Resources/app.asar/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (internal/streams/readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[2024-06-03 19:14:24] [INFO] Connection for dev closed, MQTT.js onClose trigger
... and more and more

```
<img width="1025" alt="image" src="https://github.com/emqx/MQTTX/assets/3981276/7c11b13a-5297-47c7-8d04-915decfb68ad">

<img width="1025" alt="image" src="https://github.com/emqx/MQTTX/assets/3981276/255ebccf-5b46-4c44-8226-71dc7c705666">

**Comment by blankhang** [comment] 2024-06-03 12:06
```log
[2024-06-03 20:01:00] [INFO] Assigned ID 59e320e6-eb28-4399-bb69-5f8be5856bd6 to MQTTX client
[2024-06-03 20:01:00] [INFO] Client dev connected using MQTT/TCP connection at mqtt://localhost:1883
[2024-06-03 20:01:00] [INFO] Successful connection for dev, MQTT.js onConnect trigger
[2024-06-03 20:01:00] [INFO] Resubscription in progress for topic: device/device_user_login_status
[2024-06-03 20:01:00] [INFO] Saved topic: device/device_user_login_status
[2024-06-03 20:01:00] [INFO] Successfully subscribed to topic: device/device_user_login_status
[2024-06-03 20:03:10] [DEBUG] [dev] Sent packet: {"cmd":"pingreq"}
[2024-06-03 20:03:10] [DEBUG] [dev] Received packet: {"cmd":"pingresp","retain":false,"qos":0,"dup":false,"length":0,"topic":null,"payload":null}
[2024-06-03 20:03:16] [DEBUG] [dev] Sent packet: {"cmd":"disconnect"}
[2024-06-03 20:03:16] [INFO] Connection for dev closed, MQTT.js onClose trigger
[2024-06-03 20:03:16] [INFO] MQTTX client named dev with client ID mqttx_blank disconnected
[2024-06-03 20:03:18] [INFO] Assigned ID 59e320e6-eb28-4399-bb69-5f8be5856bd6 to MQTTX client
[2024-06-03 20:03:18] [INFO] Client dev connected using MQTT/TCP connection at mqtt://localhost:1883
[2024-06-03 20:03:18] [DEBUG] [dev] Received packet: {"cmd":"connack","retain":false,"qos":0,"dup":false,"length":3,"topic":null,"payload":null,"sessionPresent":false,"reasonCode":0}
[2024-06-03 20:03:18] [INFO] Successful connection for dev, MQTT.js onConnect trigger
[2024-06-03 20:03:18] [INFO] Resubscription in progress for topic: device/device_user_login_status
[2024-06-03 20:03:18] [DEBUG] [dev] Sent packet: {"cmd":"subscribe","subscriptions":[{"topic":"device/device_user_login_status","qos":2,"nl":false,"rap":false,"rh":0}],"qos":1,"retain":false,"dup":false,"messageId":42469}
[2024-06-03 20:03:18] [DEBUG] [dev] Received packet: {"cmd":"suback","retain":false,"qos":0,"dup":false,"length":4,"topic":null,"payload":null,"granted":[2],"messageId":42469}
[2024-06-03 20:03:18] [INFO] Saved topic: device/device_user_login_status
[2024-06-03 20:03:18] [INFO] Successfully subscribed to topic: device/device_user_login_status
[2024-06-03 20:04:18] [DEBUG] [dev] Sent packet: {"cmd":"pingreq"}
[2024-06-03 20:04:18] [DEBUG] [dev] Received packet: {"cmd":"pingresp","retain":false,"qos":0,"dup":false,"length":0,"topic":null,"payload":null}
[2024-06-03 20:04:20] [DEBUG] [dev] Received packet: {"cmd":"publish","retain":false,"qos":2,"dup":false,"length":64,"topic":"device/device_user_login_status","payload":{"type":"Buffer","data":[123,34,109,115,103,34,58,34,228,186,140,231,187,180,231,160,129,229,183,178,229,164,177,230,149,136,34,125]},"messageId":1}
[2024-06-03 20:04:20] [DEBUG] [dev] Sent packet: {"cmd":"pubrec","messageId":1}
log

and topic message didn't show correctly it's on the debug log but not on UI?
<img width="1025" alt="image" src="https://github.com/emqx/MQTTX/assets/3981276/b3fa6700-50a3-46fa-a355-3b3260886008">

**Comment by ysfscream** [comment] 2024-06-04 07:20
Hi, thank you for your feedback. It appears to be a bug. However, I cannot reproduce this issue. Please clarify the Auth configuration you are using. I've tried setting an incorrect username and updating it with the correct information, but it doesn't trigger the reconnect method.

**Comment by blankhang** [comment] 2024-06-04 07:22
use correct username/password and then change to incorrect username/password then i think will show

**Comment by ysfscream** [comment] 2024-06-04 07:49
Sorry, but there's indeed no trigger. What's your MQTT Broker?

**Comment by ysfscream** [comment] 2024-07-17 03:02
If there is no update, I will close this issue. Thanks.

**Closed by ysfscream** 2024-07-17 03:02 UTC
Labels: bug, desktop
