### ISSUE TITLE
[Bug] Issue with Data Precision Loss in JSON Messages in MQTTX

### ISSUE THREAD

**Issue by nbptzjp** [emqx/MQTTX#1505] opened 2023-11-24 06:23 UTC
#### What did I do

1. Used Java code to call EMQX's interface to send JSON-type messages.
2. Created two connections in MQTTX: Connection A to send MQTT messages, and Connection B to subscribe and receive messages sent by Connection A.

#### What happened

原始报文
`{"code":10271,"value":{"phoneBTMac":"11:1A:2B:3C:4D:9E","pinCode":522676,"serializable":1724442618569203714,"userId":1688888483063664642}}`
mqttx接收到的报文
`{
  "code": 10271,
  "value": {
    "phoneBTMac": "11:1A:2B:3C:4D:9E",
    "pinCode": 245405,
    "serializable": 1724442001931018200,
    "userId": 1688888483063664600
  }
}`

#### Expected

报文中的long类型数据精度丢失

#### Environment

- OS: OS version, e.g. win11
- MQTTX version, e.g.  v1.9.6

#### More detail

More detail include `log` information or screenshot

**Comment by nbptzjp** [comment] 2023-11-24 06:28
![image](https://github.com/emqx/MQTTX/assets/36099349/2054332f-da3d-4bc5-a995-0e82b6f274b2)
A链接发送报文 
{"code":10271,"value":{"phoneBTMac":"11:1A:2B:3C:4D:9E","pinCode":522676,"serializable":1724442618569203714,"userId":1688888483063664642}}
B链接分别用json和text接收报文
![image](https://github.com/emqx/MQTTX/assets/36099349/98d8d8d7-4372-4857-a91a-385e66a15dc9)




日志
[2023-11-24 14:27:24] [INFO] A链接 message arrived: message added "message_3f7676ef-896a-42d8-a2fe-4a22c95a3bc4" and added to topic: "sys/2679047356254564354/data_upload", payload: "{\n  \"code\": 10271,\n  \"value\": {\n    \"phoneBTMac\": \"11:1A:2B:3C:4D:9E\",\n    \"pinCode\": 522676,\n    \"serializable\": 1724442618569203700,\n    \"userId\": 1688888483063664600\n  }\n}" MQTT.js onMessageArrived trigger with Properties: undefined
[2023-11-24 14:27:24] [INFO] A链接 successfully published message "{\"code\":10271,\"value\":{\"phoneBTMac\":\"11:1A:2B:3C:4D:9E\",\"pinCode\":522676,\"serializable\":1724442618569203714,\"userId\":1688888483063664642}}" to topic "sys/2679047356254564354/data_upload" with Properties: {}

**Comment by ysfscream** [comment] 2023-11-28 01:51
Hi, thanks for your feedback. It seems this issue is related to the limitations of JSON when handling large numbers, particularly during parsing and conversion. We've noted similar issues as discussed in Issue #1410 #740 #1454 

We aim to address this in the upcoming MQTTX 1.9.7 release.

**Comment by ni00** [comment] 2023-11-29 10:39
Hello @nbptzjp @ysfscream , this is a common JSON.parse problem caused by a JS defect. I suspect the same issue exists in mqttx-cli and the web end. If no one is currently fixing this issue, I plan to try using the library [json-bigint](https://github.com/sidorares/json-bigint) to solve it and submit a PR (Although I feel that this solution may cause some performance issues when processing a large amount of JSON formatting).

**Comment by ysfscream** [comment] 2023-12-08 09:43
This issue has been fixed in the [MQTTX v1.9.7 release](https://github.com/emqx/MQTTX/releases/tag/v1.9.7). Thank you for your feedback.

**Closed by ysfscream** 2023-12-08 09:43 UTC
Labels: bug, desktop
