### ISSUE TITLE
[Bug] import backup data report sqlite error

### ISSUE THREAD

**Issue by zhouding** [emqx/MQTTX#1696] opened 2024-06-17 01:58 UTC
#### What did I do

I got a new computer, so I clicked "Data Backup" and got a JSON file. However, when I tried to import the JSON file using "Data Recovery", I received an error message, indicating that only one MQTT connection was found. In fact, I have 11 connections.

#### What happened

Get an error.
![image](https://github.com/emqx/MQTTX/assets/3396199/d261f5f6-2a9f-4c78-8756-7a3445ccff24)

#### Expected

transfer data between two computers

#### Environment

- OS: OS version,Windows10/11
- MQTTX version, e.g. v1.10.0

#### More detail

More detail include `log` information or screenshot

**Comment by ysfscream** [comment] 2024-06-17 09:25
I have tried to backup and restore 11 connections on my side and encountered no issues. Could you please confirm if all your operations were performed within version 1.10.0? Also, the error message in your screenshot needs to be completed. Could you provide a full error message? This would help me understand the issue better and resolve it.

Thank you!

**Comment by zhouding** [comment] 2024-06-19 14:00
![image](https://github.com/emqx/MQTTX/assets/3396199/96f76d64-cfe6-44d1-a9d9-a815e218989e)
after“clear history data” ,data backup& data recovery was successful. i guess  too much data will caused this problem.

**Comment by ysfscream** [comment] 2024-06-20 02:42
OK, this might be caused by message data. If you can, let us know how many messages you have pub/sub. We will use this data to reproduce the issue and improve this feature. Thanks!

**Comment by zhouding** [comment] 2024-06-20 02:56
it's not safe to upload data in public area, so please give me an email address to send.

**Comment by ysfscream** [comment] 2024-06-20 03:37
@zhouding yusf@emqx.io, thank you for your support and contribution.

I will try to reproduce the issue on my end. Your data will be saved locally and will not be shared anywhere. Once the optimization is complete, I will delete it immediately. Thank you!

**Comment by ysfscream** [comment] 2024-07-16 09:54
The issue has been fixed in https://github.com/emqx/MQTTX/releases/tag/v1.10.1. Please update and use it. Thank you.

**Closed by ysfscream** 2024-07-16 09:54 UTC
Labels: bug, desktop
