### ISSUE TITLE
UI isn't normal

### ISSUE THREAD

**Issue by tuoeg** [emqx/MQTTX#1089] opened 2022-10-08 11:42 UTC
#### What did I do

i download the exe,but can't work

#### What happened

![image](https://user-images.githubusercontent.com/49616374/194705656-a3c29db9-6a2c-4dae-8d5f-5b41e27adc3c.png)

**Comment by ysfscream** [comment] 2022-10-10 03:26
Sorry for my late reply, have you downloaded MQTT X before? Maybe you can delete the `%USERPROFILE%\AppData\Roaming\MQTTX\MQTTX.db` file under this path and reopen the MQTT X to try.

**Comment by tuoeg** [comment] 2022-10-10 06:52
> Sorry for my late reply, have you downloaded MQTT X before? Maybe you can delete the `%USERPROFILE%\AppData\Roaming\MQTTX\MQTTX.db` file under this path and reopen the MQTT X to try.

I delete the db file,reopen the exe，also not useful

**Comment by ysfscream** [comment] 2022-10-12 02:00
Please uninstall the MQTT X on your machine, and redownload https://github.com/emqx/MQTTX/releases/tag/v1.8.3 again.

**Comment by ysfscream** [comment] 2022-10-12 02:40
Duplicate of #968

**Closed by ysfscream** 2022-10-12 02:40 UTC
Labels: bug, Desktop
