### ISSUE TITLE
[Bug] MQTT protocol not showing up in "host" dropdown

### ISSUE THREAD

**Issue by JorgenSQ** [emqx/MQTTX#1449] opened 2023-10-16 08:28 UTC
#### What did I do

Ran the latest docker image with the standard commands per instrauctions on https://mqttx.app/downloads

#### What happened

When creating a new connection, i expect `mqtt`/`mqtts `in adition to `ws`/`wss `to be available as options

#### Expected

Only `ws` and `wss` options are available to choose as the protocol for the host connection string

#### Environment

- OS: Ubuntu on WSL
- MQTTX version: whatever is in the latest docker-image

#### More detail

![image](https://github.com/emqx/MQTTX/assets/89529095/fa6ab581-c7d5-489f-ba85-6276d616a509)

**Comment by red-avtovo** [comment] 2023-10-16 08:44
Same here. Detected both on 1.9.6 and 1.8.3

**Comment by ysfscream** [comment] 2023-10-17 03:34
Duplicate of #1416

**Closed** 2023-12-08 09:53 UTC
Labels: help wanted, wontfix, web

**Comment by SR-G** [comment] 2024-10-20 20:32
I have the same need : in a "homelab" installation (that means, not exposed over internet), while trying MQTTX deployed in a docker container (but still with a local HTTPS valid certificate only available locally to reach the MQTTX UI), i can't use mqtt:// (TCP) direct protocol (whereas my mosquitto server IS exposed on my home network only through TCP, and this is perfectly fine).

Any way to bypass these protocol restrictions, like an extra parameter ("--allow-tcp-connections") ?
