### ISSUE TITLE
[Bug] Sqlite errors (MQTTX won't open)

### ISSUE THREAD

**Issue by mniesen** [emqx/MQTTX#995] opened 2022-07-20 17:39 UTC
#### What did I do

I have installed MQTTX.

#### What happened

After installing MQTTX (for my user only) it won't open. Running MQTTX directly via cmd will show sqlite errors.

#### Environment

- OS: Windows 10 21H2
          -> On my device I also have Folder Redirection and Roaming User Profiles, because of that my appdata location is located on a 
               network share. 
- MQTTX version, v1.8.0 desktop client

#### More detail
I can confirm that there is an MQTTX.db file, when I read that file it is empty. 
Perhaps because my appdata location is a UNC path the sqlite module in nodejs can't write to the database file?

Below is the error I get (read via cmd).
```
query failed: CREATE TABLE "temp_migration_table" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "timestamp" bigint NOT NULL, "name" varchar NOT NULL)
error: Error: SQLITE_IOERR: disk I/O error
--> in Database#all('CREATE TABLE "temp_migration_table" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "timestamp" bigint NOT NULL, "name" varchar NOT NULL)', undefined, [Function: handler])
    at SqliteQueryRunner.<anonymous> (C:\Users\mniesen\AppData\Local\Programs\MQTTX\resources\app.asar\node_modules\typeorm\driver\sqlite\SqliteQueryRunner.js:57:56)
    at step (C:\Users\mniesen\AppData\Local\Programs\MQTTX\resources\app.asar\node_modules\typeorm\node_modules\tslib\tslib.js:143:27)
    at Object.next (C:\Users\mniesen\AppData\Local\Programs\MQTTX\resources\app.asar\node_modules\typeorm\node_modules\tslib\tslib.js:124:57)
    at C:\Users\mniesen\AppData\Local\Programs\MQTTX\resources\app.asar\node_modules\typeorm\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\mniesen\AppData\Local\Programs\MQTTX\resources\app.asar\node_modules\typeorm\node_modules\tslib\tslib.js:113:16)
    at execute (C:\Users\mniesen\AppData\Local\Programs\MQTTX\resources\app.asar\node_modules\typeorm\driver\sqlite\SqliteQueryRunner.js:51:64)
    at SqliteQueryRunner.<anonymous> (C:\Users\mniesen\AppData\Local\Programs\MQTTX\resources\app.asar\node_modules\typeorm\driver\sqlite\SqliteQueryRunner.js:83:46)
    at step (C:\Users\mniesen\AppData\Local\Programs\MQTTX\resources\app.asar\node_modules\typeorm\node_modules\tslib\tslib.js:143:27) {
  errno: 10,
  code: 'SQLITE_IOERR',
  __augmented: true
}
(node:26272) UnhandledPromiseRejectionWarning: QueryFailedError: SQLITE_IOERR: disk I/O error
    at new QueryFailedError (C:\Users\mniesen\AppData\Local\Programs\MQTTX\resources\app.asar\node_modules\typeorm\error\QueryFailedError.js:12:28)
    at Statement.handler (C:\Users\mniesen\AppData\Local\Programs\MQTTX\resources\app.asar\node_modules\typeorm\driver\sqlite\SqliteQueryRunner.js:77:38)
    at Statement.replacement (C:\Users\mniesen\AppData\Local\Programs\MQTTX\resources\app.asar\node_modules\sqlite3\lib\trace.js:25:27)
(Use `MQTTX --trace-warnings ...` to show where the warning was created)
(node:26272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26272) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ysfscream** [comment] 2022-07-22 16:59
@oceanlvr Could you please help with this issue? This looks like a problem with creating a `temp_migration_table`.

**Comment by oceanlvr** [comment] 2022-07-23 14:37
> On my device I also have Folder Redirection and Roaming User Profiles, because of that my appdata location is located on a network share.
Have you ever tried placing it locally? The problem may be caused by read and write permissions to the folder on a network share

**Comment by mniesen** [comment] 2022-07-23 14:55
What do you mean by placing it locally?  I cannot disable folder redirection.

Could it be something to do with the share being an UNC path?

**Comment by oceanlvr** [comment] 2022-07-23 15:44
I think it might be caused by folder redirection or folder access Permissions. This is the problem with TypeORM maybe can't handle the UNC path, I think you could just  try to use a UNC path with typeorm, and verify that it is accessible.

**Comment by oceanlvr** [comment] 2022-07-23 15:55
you could build you own MQTT X locally (use another static app data path)
1.  replace `APP.getPath('userData')` to  some other directory like `D://MQTTX/data`
2. npm run build

**Comment by mniesen** [comment] 2022-07-23 16:02
Do you use the ```process.env.APPDATA``` variable or a static path, cause if I go to my appdata (on that network share) I see an empty database file.

**Comment by oceanlvr** [comment] 2022-07-23 16:20
yes ,`appdata-path` libarary use `process.env.APPDATA`  variable. @mniesen 

https://github.com/emqx/MQTTX/blob/main/src/database/database.config.ts#L34-L41
https://github.com/demurgos/appdata-path/blob/master/lib/index.js#L26-L43

this is the source code, maybe you could remove it and test agagin.

<img width="641" alt="image" src="https://user-images.githubusercontent.com/36698124/180613688-a4109740-8e58-4d1a-af2d-a6b176b9420e.png">

**Comment by mniesen** [comment] 2022-07-23 16:26
I will try debugging it and see if I can solve it, that will take some time. I will let you now when I have more news.

**Comment by oceanlvr** [comment] 2022-07-23 16:29
Thanks, welcome to continue feedback.

**Comment by ysfscream** [comment] 2022-10-12 02:09
Thanks for the feedback, if there are no more questions, I will close the issue.

**Closed by ysfscream** 2022-10-12 02:09 UTC
Labels: bug, Desktop
