### ISSUE TITLE
[Bug] Text appearing as blocks in some dialogs with Ubuntu Desktop

### ISSUE THREAD

**Issue by barrettc** [emqx/MQTTX#1698] opened 2024-06-18 18:05 UTC
#### What did I do

Installed MQTTX via the Snap Store

#### What happened

I have a self-signed certificate I was trying to configure MQTTX to use. When I clicked on the dialog to point to the CA file, the dialog that pops up is not readable because of the blocks you can see in my screenshot.

#### Expected

Dialog should render readable ASCII

#### Environment

- OS: Ubuntu Desktop 24.04 LTS
- MQTTX version 1.10.0

#### More detail

More detail include `log` information or screenshot
![Screenshot from 2024-06-18 13-01-30](https://github.com/emqx/MQTTX/assets/695176/c6949887-2931-4e54-90db-193a11b31106)

**Comment by ysfscream** [comment] 2024-06-19 09:48
Hi, I'm not entirely sure what the root cause of this issue is.

MQTTX calls the system dialog and does not require or have the capability to adapt it. You might want to try downloading the `AppImage` or `deb` package from the official website mqttx.app and install it to see if that resolves the issue. Alternatively, you can also try installing it from Flathub.

Additionally, please check if your system is missing English fonts.

Thanks

**Comment by barrettc** [comment] 2024-06-19 14:34
Thanks - I'll try out your suggestions and let you know

**Comment by ysfscream** [comment] 2024-07-17 03:05
If there is no update, I will close this issue. Thanks.

**Closed by ysfscream** 2024-07-17 03:05 UTC
Labels: bug, desktop, Linux
