### ISSUE TITLE
[Bug] MQTTX 1.9.5 for Windows unable to display payload messages

### ISSUE THREAD

**Issue by Guang-X** [emqx/MQTTX#1414] opened 2023-09-12 07:50 UTC
![image](https://github.com/emqx/MQTTX/assets/123046375/01c167c1-953c-4c16-b700-43a238553765)

![image](https://github.com/emqx/MQTTX/assets/123046375/0f7e7774-d1c6-40b6-a9e1-f27237986489)

**Comment by ysfscream** [comment] 2023-09-12 09:41
Sorry for the inconvenience. This issue seems to be a duplicate of #1405.

We suspect that it may be caused by a failed database migration. Unfortunately, we are currently unable to identify the root cause of the issue.

Could you please let us know how you upgraded to version 1.9.5? Did you use the automatic upgrade feature or did you manually download and install MQTTX? To resolve the issue, we suggest trying to uninstall MQTTX and then reinstalling it. Thank you for your patience and understanding.

**Comment by ni00** [comment] 2023-09-14 09:29
Hello @Guang-X , thank you for your feedback. Could you provide the `MQTTX.db ` file in the following directory `%USERPROFILE%\AppData\Roaming\MQTTX` ? It would help me analyze and track this issue.

If you have used some sensitive data for connection before, you can use [sqlite browser](https://sqlitebrowser.org/) to desensitize this db file before sharing it with me. Here is my email: `mail@nixiaobai.com`.

Of course, if you don't want to do this, you can directly delete the ` MQTTX.db` file. In theory, the MQTTX software should return to normal upon restarting.

---

你好 @Guang-X ，感谢你的反馈。你是否能提供你以下目录 `%USERPROFILE%\AppData\Roaming\MQTTX ` 的 `MQTTX.db` 文件，便于我对这个issue进行分析和追踪？这是我的邮箱，十分感谢： `mail@nixiaobai.com`。

如果你之前使用过一些敏感数据进行连接的话，你可以使用sqlite工具 [sqlite browser](https://sqlitebrowser.org/) 对这个db文件进行脱敏，然后再分享给我。

当然，如果你并不想这样做，你可以直接删除这个 MQTTX.db 文件，理论上，再次启动MQTTX，软件应该会恢复正常使用。

**Comment by ysfscream** [comment] 2024-06-07 09:49
if there is no update, I will close this issue. thanks.

**Closed by ysfscream** 2024-06-07 09:49 UTC
Labels: bug, migration, desktop, Windows
