### ISSUE TITLE
Enter the client and flash a white screen

### ISSUE THREAD

**Issue by zhangxiansheng123** [emqx/MQTTX#1716] opened 2024-07-09 13:35 UTC
Enter the client and flash a white screen

**Comment by ysfscream** [comment] 2024-07-10 01:52
Hi @zhangxiansheng123,

I am currently focused on fixing this issue, which I believe might be caused by an error with the database file, as discussed in PR #1711. However, I am not certain about the exact cause in your case. Please follow these steps:

1. If your data does not involve privacy concerns, you can share the `MQTTX.db` file with me at yusf@emqx.io for further investigation.
2. **Delete the `MQTTX.db` file**:
   - **Linux**: `~/.config/MQTTX/`
   - **macOS**: `~/Library/Application Support/MQTTX/`
   - **Windows**: `%USERPROFILE%\AppData\Roaming\MQTTX/`
3. **Restart the app**.
4. **If you can still access the settings page**, please click on data export to check for the error cause.
5. **Let me know your current version**, and if necessary, upgrade to the latest version.

Thank you for your feedback.

Best regards

**Comment by ysfscream** [comment] 2024-07-17 03:01
The issue has been fixed in https://github.com/emqx/MQTTX/releases/tag/v1.10.1. Please update and use it. Thank you.

**Closed by ysfscream** 2024-07-17 03:01 UTC
Labels: bug, desktop
