### ISSUE TITLE
JSON content topic corrupting db

### ISSUE THREAD

**Issue by friesendrywall** [emqx/MQTTX#457] opened 2021-01-22 20:28 UTC
I find that topics receiving certain types of JSON cause the app the crash, and corrupt the database as well.  This is using MQTT version 5.0

**Comment by ysfscream** [comment] 2021-01-23 15:37
Hi, sorry about that and thanks for your feedback. Could you please describe its details? You can follow the `issue-template`, which will be better. :)

[bug-report-template](https://raw.githubusercontent.com/emqx/MQTTX/dev/1.4.3/.github/ISSUE_TEMPLATE/bug_report.md)

```
---
name: Bug report
about: Create a report to help us improve
title: "[Bug] the title of bug report"
labels: bug
assignees: ''

---

## what did I do

something you have done.

## what happened

get an error

## environment

- ubuntu

## log/Screenshot/context

xxxx
```

**Comment by ysfscream** [comment] 2021-05-11 05:52
Duplicate of #524. We will discuss it there.

**Closed by ysfscream** 2021-05-11 05:52 UTC
Labels: bug, enhancement
