### ISSUE TITLE
[BUG]Need to prompt when publishing fails

### ISSUE THREAD

**Issue by Rory-Z** [emqx/MQTTX#525] opened 2021-03-02 08:14 UTC
#### What did I do

I use emqx broker and refuse to publish for all topics. When I use MQTTX to publish a message whose Qos is not 0, emqx broker rejects the message, but MQTTX does not give any prompt

#### Expected

Need to prompt when publishing fails

#### Environment

- OS: MacOS 10.15.7
- MQTTX version: v1.4.2

**Comment by oceanlvr** [comment] 2021-03-02 10:19
Thanks for your suggestion. I'll try to reproduce and enhance the prompt.

**Comment by oceanlvr** [comment] 2021-03-05 07:28
I'll reopen this issue when I reproduce this problem.

Here is my local emqx broker `ACL.conf` configure:

```conf
{deny, all, publish,["testtopic/1"]}.
{allow, all}.
```

And when I pub `testtopic/1` with Qos 1 or Qos 2:

![image](https://user-images.githubusercontent.com/36698124/110081712-4e446080-7dc7-11eb-96c4-2426073e3c7b.png)

**Comment by ysfscream** [comment] 2021-07-07 02:14
It looks like nothing is wrong now and I will close this issue.

**Closed by ysfscream** 2021-07-07 02:14 UTC
Labels: bug, enhancement
